name: Security Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' 

    - name: Restore
      run: dotnet restore

    - name: Audyt pakietow NuGet
      shell: pwsh
      run: |
        $out = dotnet list package --vulnerable 2>&1 
        if ($out -match "vulnerable packages") {
          Write-Error "Wykryto podatne pakiety! Sprawdz raport."
          Write-Output $out
          exit 1
        }
        Write-Output "Brak znanych podatnosci."

   - name: Build z analizatorami (SAST)
      run: >
        dotnet build --configuration Release
        /p:TreatWarningsAsErrors=false
        /p:PublishReadyToRun=false
        -r win-x64
        --no-restore

    - name: Generuj SBOM
      shell: pwsh
      run: |
        dotnet tool install --global Microsoft.Sbom.DotNetTool
        $env:PATH += ";$env:USERPROFILE\.dotnet\tools"
        # Poprawione łamanie linii (`) oraz dodany wymagany parametr -ns
        sbom-tool generate -b ./bin/Release -bc . `
          -pn SecurityAuditApp -pv 1.0.0 -ps Student -ns "https://audit.local"

    - name: Upload SBOM jako artefakt
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: '**/manifest.spdx.json' 

    - name: Podpisz skrypt PowerShell
      shell: pwsh
      run: |
      
        if (-not (Test-Path ".\deploy.ps1")) { New-Item -Path ".\deploy.ps1" -ItemType File -Value "Write-Output 'Deploy'" }
        
      
        $cert = New-SelfSignedCertificate `
          -Subject "CN=Lab10 Student Developer" `
          -Type CodeSigningCert `
          -CertStoreLocation "Cert:\CurrentUser\My" `
          -NotAfter (Get-Date).AddYears(2)
          
        Set-AuthenticodeSignature `
          -FilePath ".\deploy.ps1" `
          -Certificate $cert
          
        $sig = Get-AuthenticodeSignature ".\deploy.ps1"
        Write-Output "Status podpisu: $($sig.Status)"
